var http = require('http')
var fs  = require('fs')

var server = http.createServer(function(req, res ){
    res.writeHead(200, {'Content-type': 'text/plain'})
    fs.writeFileSync('text1.txt', 'This file is generated by nodejs')
    var myRS = fs.createReadStream(__dirname+'/text1.txt', 'utf-8')
    myRS.pipe(res)
});
server.listen(3000)
console.log('serever is running')